version: '3.6'
services:
  elk:
   build: .
   ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
   container_name: elk
  zipkin:
   image: openzipkin/zipkin
   ports:
    - 9411:9411
   container_name: zipkin