server:
  port: 9999

spring:
    zipkin.baseUrl: http://localhost:9411
    sleuth.sampler.percentage: 1

zuul:
  ignored-services: '*'
  routes:
   product-service:
     path: /products/**
     stripPrefix: false

eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8888/eureka/

management:
  security:
    enabled: false

